name: "CSharp"

on:
  push:
    branches: [master, develop]
  pull_request:
    types: [review_requested, ready_for_review]

jobs:
  Build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup dotnet
        uses: timheuer/bootstrap-dotnet@v1
        with:
          dotnet-version: '4.0.x'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x86

      - name: Build project
        run: |
          msbuild $Env:GITHUB_WORKSPACE\PDFPatcher.sln /target:restore /p:Platform=Win32 /property:Configuration=Debug /property:RestorePackagesConfig=true
          msbuild $Env:GITHUB_WORKSPACE\PDFPatcher.sln /target:build /p:Platform=Win32 /property:Configuration=Debug /property:RestorePackagesConfig=true

      # Archive
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: PDFPatcher-Debug
          path: bin/Debug/PDFPatcher.exe
